#!/usr/bin/env bash
# Adds "Convert with MagnifyFactory" to the right-click menu on Linux file
# managers, and registers the app for "Open With" everywhere via a standard
# .desktop launcher. Per-user only (installs under ~/.local/share) — no root
# required. Run unregister_context_menu.sh to remove it again.
#
# Usage: ./register_context_menu.sh [path-to-MagnifyFactory-binary]
# Defaults to ../build/MagnifyFactory relative to this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXE_PATH="${1:-$SCRIPT_DIR/../build/MagnifyFactory}"

if [ ! -e "$EXE_PATH" ]; then
    echo "Error: $EXE_PATH not found. Build it first, or pass the binary's path as an argument." >&2
    exit 1
fi
EXE_PATH="$(readlink -f "$EXE_PATH")"
if [ ! -x "$EXE_PATH" ]; then
    echo "Error: $EXE_PATH exists but is not executable." >&2
    exit 1
fi

ICON_PATH="$(readlink -f "$SCRIPT_DIR/../resources/icon.png")"
MIME_TYPES="video/mp4;video/x-matroska;video/quicktime;video/x-msvideo;video/mpeg;video/webm;video/x-flv;audio/mpeg;audio/wav;audio/x-flac;audio/aac;audio/mp4;audio/ogg;image/png;image/jpeg;image/webp;image/avif;image/bmp;image/tiff;image/gif;application/pdf;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;application/vnd.openxmlformats-officedocument.presentationml.presentation;application/zip;application/x-7z-compressed;"

# --- .desktop launcher: makes MagnifyFactory show up in "Open With" on any
# XDG-compliant file manager (Nautilus, Dolphin, Thunar, Nemo, ...), and in
# app launchers/menus.
APPS_DIR="$HOME/.local/share/applications"
mkdir -p "$APPS_DIR"
cat > "$APPS_DIR/magnifyfactory.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=MagnifyFactory
Comment=Convert video, audio, images, PDFs, documents, and archives
Exec="$EXE_PATH" %f
Icon=$ICON_PATH
Terminal=false
Categories=AudioVideo;
MimeType=$MIME_TYPES
EOF

# --- GNOME Files (Nautilus) "Scripts" submenu — a direct one-click
# "Convert with MagnifyFactory" entry, applies to whatever is selected.
NAUTILUS_SCRIPTS_DIR="$HOME/.local/share/nautilus/scripts"
mkdir -p "$NAUTILUS_SCRIPTS_DIR"
NAUTILUS_SCRIPT="$NAUTILUS_SCRIPTS_DIR/Convert with MagnifyFactory"
cat > "$NAUTILUS_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by register_context_menu.sh — do not edit by hand.
IFS=\$'\n'
for f in \$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    "$EXE_PATH" "\$f" &
done
EOF
chmod +x "$NAUTILUS_SCRIPT"

# --- KDE Dolphin service menu — same direct entry for Plasma. Installed to
# both the Plasma 6 / Plasma 5.24+ location and the older Plasma 5 one,
# since either might be what a given system actually reads.
DOLPHIN_MENU_CONTENT="[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/allfiles;
Actions=convertWithMagnifyFactory;
Icon=$ICON_PATH

[Desktop Action convertWithMagnifyFactory]
Name=Convert with MagnifyFactory
Icon=$ICON_PATH
Exec=\"$EXE_PATH\" %f
"
mkdir -p "$HOME/.local/share/kio/servicemenus"
echo "$DOLPHIN_MENU_CONTENT" > "$HOME/.local/share/kio/servicemenus/magnifyfactory.desktop"
mkdir -p "$HOME/.local/share/kservices5/ServiceMenus"
echo "$DOLPHIN_MENU_CONTENT" > "$HOME/.local/share/kservices5/ServiceMenus/magnifyfactory.desktop"

# Refresh caches where the tools exist (harmless no-ops otherwise).
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true

echo "Registered MagnifyFactory context-menu integration for the current user, pointing to:"
echo "  $EXE_PATH"
echo
echo "- GNOME Files (Nautilus): right-click a file -> Scripts -> \"Convert with MagnifyFactory\""
echo "- KDE Dolphin: right-click a file -> \"Convert with MagnifyFactory\""
echo "- Any file manager: right-click -> Open With -> MagnifyFactory"
echo
echo "Run unregister_context_menu.sh to remove it."
